kind: pipeline
type: docker
name: build

trigger:
  event:
    - push
    - tag
    - pull_request
steps:
  - name: tidy
    image: golang:1.19.0
    commands:
      - go mod tidy
      - git diff --exit-code -- go.mod go.sum
  - name: lint
    image: golangci/golangci-lint:v1.46.2
    commands:
      - golangci-lint run -v -E gofmt
  - name: vet
    image: golang:1.19.0
    commands:
      - go vet -race ./...
  - name: build
    image: golang:1.19.0
    commands:
      - go build -race .
  - name: gosec
    image: securego/gosec:2.12.0
    commands:
      - gosec -tests ./...
